### PR TITLE
Lets_Graph_It

### PR DESCRIPTION
**Pull request by ziggawho**
This file discusses some of the pros/cons of using a graph database for content management.

### CODE REVIEW

**Comment by ziggawho** [comment]
Dream team @zmschonberger @BackwardsBadger @invisiblenanjia @curfuffled @vickynowis @sdlippel, this is ready for comments/thoughts, etc... Apologies for the lateness, I ran out of Mountain Dew and could only find the cheap knock-off version of it at Trader Joe's. Note: Cane sugar does not provide the same kick as HFCS :stuck_out_tongue:

**Comment by invisiblenanjia** [comment]
Up

**Comment by BackwardsBadger** [comment]
Looks good.  Love the reference to online dating, I feel your pain

**Comment by zmschonberger** [comment]
Well done Zig.  You could also make this a .md file for readability purposes.

**Comment by vickynowis** [comment]
I only heard about graph databases...learnt something new from this.
ship it

**Pull request merged**
