### PR TITLE
Impact of technology choice

### PR DESCRIPTION
**Pull request by vickynowis**
Ready for feedback!
need feedback

### CODE REVIEW

**Comment by vickynowis** [comment]
@zmschonberger @ziggawho @invisiblenanjia @BackwardsBadger @sdlippel @curfuffled any thoughts?

**Comment by curfuffled** [comment]
Great overview of the risks/implications. 
Particularly :+1: gif selection.

**Comment by sdlippel** [comment]
th

would just maybe add on "determines the rate at which we can learn about our product from customers" under the implications part of technology choices!

**Comment by zmschonberger** [comment]
Great writeup.  :+1:

**Comment by ziggawho** [comment]
Nice writeup! Definitely makes it clear how important upfront planning when making technology choices - at the end of the day, if you don't have the right strategy, you shouldn't make any technology decisions! :+1:

**Pull request merged**
